# -*- coding: utf-8 -*-
"""Weather forecasting ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVoI_0kGgjgH-SwoQEro2uRtSpnZsfr_
"""

!pip -q install statsmodels tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from statsmodels.tsa.arima.model import ARIMA
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("weather_temperature.csv")

df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

print(df.head())

temps = df['temp']

plt.figure(figsize=(10,4))
plt.plot(temps)
plt.title("Daily Temperature Trend")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()

train_size = int(len(temps) * 0.8)
train, test = temps[:train_size], temps[train_size:]

"""ARIMA MODEL"""

model = ARIMA(train, order=(5,1,0))
model_fit = model.fit()

arima_pred = model_fit.forecast(steps=len(test))

mae = mean_absolute_error(test, arima_pred)
rmse = np.sqrt(mean_squared_error(test, arima_pred))

print("ARIMA MAE :", mae)
print("ARIMA RMSE:", rmse)

plt.figure(figsize=(10,4))
plt.plot(test.index, test, label="Actual")
plt.plot(test.index, arima_pred, label="ARIMA Prediction")
plt.legend()
plt.show()

"""LSTM MODEL"""

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(temps.values.reshape(-1,1))

def create_sequences(data, seq_len=10):
    X, y = [], []
    for i in range(len(data)-seq_len):
        X.append(data[i:i+seq_len])
        y.append(data[i+seq_len])
    return np.array(X), np.array(y)

seq_len = 10
X, y = create_sequences(scaled_data, seq_len)

train_size = int(len(X)*0.8)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

model = Sequential([
    LSTM(50, input_shape=(seq_len,1)),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

model.fit(X_train, y_train, epochs=20, batch_size=16)

lstm_pred = model.predict(X_test)

lstm_pred = scaler.inverse_transform(lstm_pred)
y_test_actual = scaler.inverse_transform(y_test)

mae = mean_absolute_error(y_test_actual, lstm_pred)
rmse = np.sqrt(mean_squared_error(y_test_actual, lstm_pred))

print("LSTM MAE :", mae)
print("LSTM RMSE:", rmse)

plt.figure(figsize=(10,4))
plt.plot(y_test_actual, label="Actual")
plt.plot(lstm_pred, label="LSTM Prediction")
plt.legend()
plt.show()

"""FUTURE 7-DAY FORECAST"""

last_seq = scaled_data[-seq_len:]
future_preds = []

for _ in range(7):
    pred = model.predict(last_seq.reshape(1,seq_len,1))
    future_preds.append(pred[0][0])
    last_seq = np.append(last_seq[1:], pred, axis=0)

future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1,1))

print("Next 7 days forecast:")
print(future_preds.flatten())

